### ISSUE TITLE
[bug] Missing rewriting help part

### ISSUE THREAD

**Issue by PatrickMassot** [edukera/issues#10]
Strange glitch in rule explanation:

![ch](https://cloud.githubusercontent.com/assets/14060883/26199653/23ed0612-3bcb-11e7-9514-fcfae188182f.png)

Similar problems occur for rules in the same group.

**Comment by rognierbenoit** [comment]
Missing definition text in top circle is fixed.
Bottom circle is not an error. It reads : 
```
if (if A then B) then C
```
