### ISSUE TITLE
[bug] Cannot scroll down in smaller screens

### ISSUE THREAD

**Issue by maelvls** [edukera/issues#11]
I cannot scroll down in many pages on my MBA 11".
My workaround: lower the zoom (`cmd+-`) in Safari. But this workaround is not obvious.

![capture d ecran 2017-07-25 a 18 05 21](https://user-images.githubusercontent.com/2195781/28581883-d79ef062-7163-11e7-9c4f-20b3d7d919d0.png)

UserAgent : mozilla/5.0 (macintosh; intel mac os x 10_12_5) applewebkit/603.2.4 (khtml, like gecko) version/10.1.1 safari/603.2.4
URL : https://app.edukera.com/?id=cm9vdA%3D%3D

**Comment by rognierbenoit** [comment]
Hello Maël,
thank you for your report. It is now solved.
Regards.
