### ISSUE TITLE
[BUG] Ensembles - Raisonnements - 1. Opérateurs logiques

### ISSUE THREAD

**Issue by tpelado** [edukera/issues#12]
UserAgent : mozilla/5.0 (windows nt 10.0; win64; x64; rv:56.0) gecko/20100101 firefox/56.0
URL : https://app.edukera.com/?id=c2V0bG9naWNfdHV0b18z&gid=5265025996423168

Il est par moment impossible d'utiliser toute les fonctions du logiciel (def, retour, relancer), le seul moyen de le refaire marcher est de redémarrer entièrement l'application.

**Comment by rognierbenoit** [comment]
Merci. Cela arrive de temps en temps dans la partie "Ensembles" qui est encore en beta, jusqu'à la prochaine version qui sort en janvier.
