### ISSUE TITLE
Invalid English translation for exercice Formalisation/Logic/12

### ISSUE THREAD

**Issue by strub** [edukera/issues#15]
The exercice "Formalisation/Logic/12" has an invalid english statement. The French statement is

> Tous eux qui ont écrit un roman ont lu "Les Misérables"

whereas its English counterpart is

> All of those who have written a novel, have read a novel by VH

**Comment by guillaumeduhamel** [comment]
Hi Pierre-Yves, thank you for your report, it is fixed.
Regards,
