### ISSUE TITLE
Virtual keyboard does not have \in key

### ISSUE THREAD

**Issue by dvvrd** [edukera/issues#2]
Excercise 2 asks to enter $x \in A \cup B$, but it is a bit hard to find $\in$ on a keyboard.

![edukera-in-key](https://cloud.githubusercontent.com/assets/734254/22924319/b3a5aa5c-f2b5-11e6-9a74-d4dbbcac5093.png)

**Comment by rognierbenoit** [comment]
Hello Dimitry,

indeed there is no way in the current version to enter a proposition with the virtual keyboard. We plan to fix that by september. 

There is a workarround however : just press the unification button labeled "2" in your screenshot. this will instantiate the value of "?" with value of proposition (2) .

**Comment by dvvrd** [comment]
Thank you for fast responce Benoit!

**Comment by PatrickMassot** [comment]
This is seems to be fixed in the current version. Why not closing this issue?

**Comment by rognierbenoit** [comment]
Indeed, thank you for noticing ! 

As a side note, I would add there is a more general feature request pending beyond this one : the possibility to create any proposition from the keyboard. 

There will soon be the possibility to create equation proposition with number relations like "=" "<=" ">=" ... for case base reasoning in the forthcoming chapter "arithmetic".
