### ISSUE TITLE
[enhancement] Exploration mode

### ISSUE THREAD

**Issue by PatrickMassot** [edukera/issues#4]
For teachers who want to explore Edukera before using it with students, it would be convenient to be able to unlock all exercises. I guess this possibility could be open to everybody by default but classes creators could disallow it for enrolled students.

**Comment by rognierbenoit** [comment]
That would be useful indeed. 

We plan to add by end of June a "require unlock" button. We would then send by email an unlock code that would : 
* unlock all exercises
* grant access to all chapter toolboxes

**Comment by rognierbenoit** [comment]
It is now available in current version.
